### ISSUE TITLE
Document required pwsh version

### ISSUE THREAD

**Issue by joergrenn** [IBM-Cloud/vpc-migration-tools#10]
For me using pwsh 5.1 the windows_precheck.ps1 script does not run correctly.
> the ampersand (&) character ist not allowed...
Using pwsh 7.1 its runs OK.
So I assume it needs pwsh 7 as a prerequisite?
Could you document the required pwsh version in the readme?

**Comment by robertebe26** [comment]
Hi @joergrenn,
              Please let us know why your trying to run *windows_precheck.ps1* script with pwsh. This is designed to check windows os and migration configuration, it should be ran in window with default **PowerShell**.

**Comment by joergrenn** [comment]
Hi @robertebe26 ,
the script does not work for me in the default PowerShell (pwsh). The default Powershell on most systems ist PowerShell 5.1 and there it does not work (for me using Windows Server 2012).
However when I install the newest Powershell Version 7.1 the scripts runs just fine.
This is why I think it is important to document the prerequisites for the script.
I which versions of PowerShell do you expect this script can be run?

**Comment by robertebe26** [comment]
Hi, 

We have tested based on OS flavour (windows 2012, 2012-R2 and windows 2016) with default settings. Not based on PowerShell, So please try with default settings.

**Comment by joergrenn** [comment]
I am sorry, but I have downloaded the script to a fresh windows server 2012 64 bit install from here:
[https://raw.githubusercontent.com/IBM-Cloud/vpc-migration-tools/main/os-precheck-scripts/windows_precheck.ps1](https://raw.githubusercontent.com/IBM-Cloud/vpc-migration-tools/main/os-precheck-scripts/windows_precheck.ps1)
And it does not work in the default PowerShell:
![Bildschirmfoto 2021-05-18 um 12 25 39](https://user-images.githubusercontent.com/62641471/118635982-7ba08800-b7d4-11eb-9cd1-14ff47391abc.jpg)

![Bildschirmfoto 2021-05-18 um 12 21 32](https://user-images.githubusercontent.com/62641471/118635239-a5a57a80-b7d3-11eb-9dac-0601990264e0.jpg)
If i use PowerShell Version 7.1 it works:
![Bildschirmfoto 2021-05-18 um 12 29 40](https://user-images.githubusercontent.com/62641471/118636437-fd90b100-b7d4-11eb-9308-a26b34791de5.jpg)
![Bildschirmfoto 2021-05-18 um 12 31 14](https://user-images.githubusercontent.com/62641471/118636448-fff30b00-b7d4-11eb-8d35-0c03aeeed68b.jpg)

So again, I think you need to adapt the documentation to state which Version of PowerShell the script is compatible with.

**Comment by robertebe26** [comment]
Hi @joergrenn ,

I have download iso files for windows 2012 and windows 2016 Evaluation version from Microsoft website ( https://www.microsoft.com/en-in/evalcenter/evaluate-windows-server ) and created vm in VMware, after installation I can see powershell version **3.0** in windows 2012 and **5.1** in windows 2016 and Also able to run script without any issue. Please see below screen shots

Windows 2012
<img width="837" alt="Screenshot 2021-05-20 at 6 07 38 PM" src="https://user-images.githubusercontent.com/72161750/118981184-b4d52580-b997-11eb-8ca5-6dc3da6aff27.png">

Windows 2016
<img width="1223" alt="Screenshot 2021-05-20 at 5 59 02 PM" src="https://user-images.githubusercontent.com/72161750/118981257-c4ed0500-b997-11eb-8d0b-34aad583d960.png">

Please let us know, how you getting powershell version 5.1 in windows 2012 by default? since its not coming with official windows os.
